### ISSUE TITLE
much better solution for multiple if statements

### ISSUE THREAD

**Issue by usta** [kuttamuwa/PowerShellScripts#1]
as like the situations like this
https://github.com/kuttamuwa/PowerShellScripts/blob/2f6ab34f0af65f2a127f0c94267bb906a9073263/DocPdf_Converter_GUI.ps1#L25
this can be much better solution :
$word_exts = ".doc" , ".docx"
$ext = [System.IO.Path]::GetExtension(($path));
if ( $word_exts -notcontains $ext ) {
    throw "extension of the file is not doc or docx, check it !"}
        }

**Comment by kuttamuwa** [comment]
It seems fair. I modified the file. Thanks for suggestion !
