### ISSUE TITLE
you predict that the extestion as docx but it can also be .doc file

### ISSUE THREAD

**Issue by usta** [kuttamuwa/PowerShellScripts#2]
https://github.com/kuttamuwa/PowerShellScripts/blob/2f6ab34f0af65f2a127f0c94267bb906a9073263/DocPdf_Converter_GUI.ps1#L38

in there you predict as the extension is as .docx on the other hand it can be .doc also.
do instead of using hardcoded value use [System.IO.Path]::GetExtension( method

**Comment by kuttamuwa** [comment]
was fixed. Thanks !
