### ISSUE TITLE
also you have predicted that filename doesnt have docx name in it :)

### ISSUE THREAD

**Issue by usta** [kuttamuwa/PowerShellScripts#3]
https://github.com/kuttamuwa/PowerShellScripts/blob/2f6ab34f0af65f2a127f0c94267bb906a9073263/DocPdf_Converter_GUI.ps1#L49

when you try just replace the filename also be like docxmyfile.docx :)

**Comment by kuttamuwa** [comment]
Fixed like:
`# Swap out PDF with DOCX in the Filename
            $filename = [System.IO.Path]::GetFileNameWithoutExtension($path); # file name without extension

            $Name= "$filename.docx"`

**Comment by usta** [comment]
still you are thinking that extension will be .docx :))  it might be .doc

**Comment by kuttamuwa** [comment]
Himm you pointed well but I don't think no one will named the file including pdf. However, i fixed this.
